### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by yashghelani**

### CODE REVIEW

**Review by NejcZdovc — COMMENTED** [review]
this section still have old logos

image

**Comment by matthewboulos** [comment]
Let’s update everything else while the illustrators get this done.

**Review by NejcZdovc — APPROVED** [review]

**Comment by NejcZdovc** [comment]
@matthewboulos sure. Merged. @yashghelani please follow up

**Comment by yashghelani** [comment]
@NejcZdovc Logo in animation updated in #169

**Pull request merged**
